apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockNodePort
metadata:
  name: block-node-port
  description: "Disallows all Services with type NodePort. https://kubernetes.io/docs/concepts/services-networking/service/#nodeport"
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Service